name: Dev

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.8-bullseye", "3.9-bullseye", "3.10-bullseye"]

    steps:
      - uses: "actions/checkout@v2"
      - name: "Build Docker"
        run: sh scripts/docker ${{ matrix.python-version }}
      - name: "Build Package"
        run: "docker run -p 8888:8000 -v $(pwd):/library bom-configuration sh scripts/build"
      - name: "Lint package"
        run: "docker run -p 8888:8000 -v $(pwd):/library bom-configuration sh scripts/lint"
      - name: "Run tests"
        run: "docker run -p 8888:8000 -v $(pwd):/library bom-configuration sh scripts/test"
      - name: "Run coverage"
        run: "docker run -p 8888:8000 -v $(pwd):/library bom-configuration sh scripts/coverage"
      - name: "Clean workspace"
        run: "docker run -p 8888:8000 -v $(pwd):/library bom-configuration sh scripts/clean"
