name: python lib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install pipenv invoke
        pipenv install --dev --ignore-pipfile

    - name: Run lint
      run: |
        pipenv run invoke lint

    - name: Run unit tests
      run: |
        pipenv run invoke test

    - name: Build and Release
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push'}}
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      run: |
        pipenv run invoke build publish
